require('Actor/ActorCommon')

local CfgMengdeDayPatrol = {}

CfgMengdeDayPatrol.DummyPointData =
{
	Npc = "MengdeDayPatrol",
	PosData={
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos01").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos02").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos03").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos04").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos05").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos06").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos07").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos08").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos09").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos10").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos11").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos12").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos13").pos,
		},
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos01").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos02").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos03").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos04").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos05").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos06").pos,
		},
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos01").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos02").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos03").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos04").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos05").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos06").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos07").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos08").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos09").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos10").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos11").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos12").pos,
		},
		{
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos01").pos,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos02").pos,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos03").pos,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos04").pos,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos05").pos,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos06").pos,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos07").pos,
		},
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos01").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos02").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos03").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos04").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos05").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos06").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos07").pos,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos08").pos,
		},
	},
	DirData={
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos01").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos02").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos03").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos04").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos05").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos06").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos07").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos08").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos09").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos10").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos11").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos12").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos13").rot,
		},
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos01").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos02").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos03").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos04").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos05").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos06").rot,
		},
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos01").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos02").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos03").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos04").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos05").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos06").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos07").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos08").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos09").rot,			
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos10").rot,			
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos11").rot,			
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos12").rot,
		},
		{
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos01").rot,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos02").rot,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos03").rot,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos04").rot,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos05").rot,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos06").rot,
			sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos07").rot,
		},
		{
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos01").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos02").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos03").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos04").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos05").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos06").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos07").rot,
			sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos08").rot,
		},
	},
	TimeData={
		{
			25,
			0,
			0,
			0,
			0,
			0,
			0,
			25,
			0,
			0,
			0,
			0,
			0,
		},
		{
			10,
			10,
			0,
			0,
			20,
			20,
		},
		{
			0,
			0,
			0,
			0,
			15,
			0,
			15,
			0,
			15,
			0,
			15,
			0,
		},
		{
			15,
			0,
			20,
			0,
			0,
			0,
			0,
		},
		{
			15,
			0,
			0,
			15,
			0,
			0,
			0,
			0,
		},
	},
	Pos01Pos =
	{
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos01").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos01").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos01").pos,
		sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos01").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos01").pos,
	},
	Pos02Pos =
	{
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos02").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos02").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos02").pos,
		sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos02").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos02").pos,
	},
	Pos03Pos =
	{
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos03").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos03").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos03").pos,
		sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos03").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos03").pos,
	},
	Pos04Pos =
	{
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos04").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos04").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos04").pos,
		sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos04").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos04").pos,
	},
	Pos05Pos =
	{
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos05").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos05").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos05").pos,
		sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos05").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos05").pos,
	},
	Pos06Pos =
	{
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol05Pos06").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol10Pos06").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol13Pos06").pos,
		sceneData:GetDummyPoint(3, "NpcMaleDayPatrol18Pos06").pos,
		sceneData:GetDummyPoint(3, "NpcFemaleDayPatrol14Pos06").pos,
	},
	NpcID =
	{
		1421,
		1431,
		1455,
		1461,
		1463,
	},
	DialogID =
	{
		4015142199,
		4015143199,
		4015145599,
		4015146199,
		4015146399,
	},
}

return CfgMengdeDayPatrol