using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GenshinCBTServer.Protocol
{
    public enum PropType
    {
        PROP_NONE = 0,
        // avatar props
        PROP_EXP = 1001, // avatar exp
        PROP_BREAK_LEVEL = 1002, // avatar promote level
        PROP_SMALL_TALENT_POINT = 1004,
        PROP_BIG_TALENT_POINT = 1005,
        PROP_GEAR_START_VAL = 2001,
        PROP_GEAR_STOP_VAL = 2002,
        PROP_LEVEL = 4001, // avatar level
                           // player props
        PROP_LAST_CHANGE_AVATAR_TIME = 10001,
        PROP_MAX_SPRING_VOLUME = 10002,
        PROP_CUR_SPRING_VOLUME = 10003,
        PROP_IS_SPRING_AUTO_USE = 10004,
        PROP_SPRING_AUTO_USE_PERCENT = 10005,
        PROP_IS_FLYABLE = 10006,
        PROP_IS_WEATHER_LOCKED = 10007,
        PROP_IS_GAME_TIME_LOCKED = 10008,
        PROP_IS_TRANSFERABLE = 10009,
        PROP_MAX_STAMINA = 10010,
        PROP_CUR_PERSIST_STAMINA = 10011,
        PROP_CUR_TEMPORARY_STAMINA = 10012,
        PROP_PLAYER_LEVEL = 10013, // adventure rank
        PROP_PLAYER_EXP = 10014, // adventure exp
        PROP_PLAYER_HCOIN = 10015, // mora
        PROP_PLAYER_SCOIN = 10016, // primogem
        PROP_IS_WORLD_ENTERABLE = 10017,
        PROP_IS_MP_MODE_AVAILABLE = 10018
    }
    public enum FightPropType
    {
        FIGHT_PROP_NONE = 0,
        FIGHT_PROP_BASE_HP = 1,
        FIGHT_PROP_HP = 2,
        FIGHT_PROP_HP_PERCENT = 3,
        FIGHT_PROP_BASE_ATTACK = 4,
        FIGHT_PROP_ATTACK = 5,
        FIGHT_PROP_ATTACK_PERCENT = 6,
        FIGHT_PROP_BASE_DEFENSE = 7,
        FIGHT_PROP_DEFENSE = 8,
        FIGHT_PROP_DEFENSE_PERCENT = 9,
        FIGHT_PROP_BASE_SPEED = 10,
        FIGHT_PROP_SPEED_PERCENT = 11,
        FIGHT_PROP_CRITICAL = 20,
        FIGHT_PROP_ANTI_CRITICAL = 21,
        FIGHT_PROP_CRITICAL_HURT = 22,
        FIGHT_PROP_CHARGE_EFFICIENCY = 23,
        FIGHT_PROP_ADD_HURT = 24,
        FIGHT_PROP_SUB_HURT = 25,
        FIGHT_PROP_HEAL_ADD = 26,
        FIGHT_PROP_HEALED_ADD = 27,
        FIGHT_PROP_FIRE_ADD_HURT = 40,
        FIGHT_PROP_ELEC_ADD_HURT = 41,
        FIGHT_PROP_WATER_ADD_HURT = 42,
        FIGHT_PROP_GRASS_ADD_HURT = 43,
        FIGHT_PROP_WIND_ADD_HURT = 44,
        FIGHT_PROP_ROCK_ADD_HURT = 45,
        FIGHT_PROP_ICE_ADD_HURT = 46,
        FIGHT_PROP_HIT_HEAD_ADD_HURT = 47,
        FIGHT_PROP_FIRE_SUB_HURT = 50,
        FIGHT_PROP_ELEC_SUB_HURT = 51,
        FIGHT_PROP_WATER_SUB_HURT = 52,
        FIGHT_PROP_GRASS_SUB_HURT = 53,
        FIGHT_PROP_WIND_SUB_HURT = 54,
        FIGHT_PROP_ROCK_SUB_HURT = 55,
        FIGHT_PROP_ICE_SUB_HURT = 56,
        FIGHT_PROP_EFFECT_HIT = 60,
        FIGHT_PROP_EFFECT_RESIST = 61,
        FIGHT_PROP_FREEZE_RESIST = 62,
        FIGHT_PROP_TORPOR_RESIST = 63,
        FIGHT_PROP_DIZZY_RESIST = 64,
        FIGHT_PROP_FREEZE_SHORTEN = 65,
        FIGHT_PROP_TORPOR_SHORTEN = 66,
        FIGHT_PROP_DIZZY_SHORTEN = 67,
        FIGHT_PROP_MAX_FIRE_ENERGY = 70,
        FIGHT_PROP_MAX_ELEC_ENERGY = 71,
        FIGHT_PROP_MAX_WATER_ENERGY = 72,
        FIGHT_PROP_MAX_GRASS_ENERGY = 73,
        FIGHT_PROP_MAX_WIND_ENERGY = 74,
        FIGHT_PROP_MAX_ICE_ENERGY = 75,
        FIGHT_PROP_MAX_ROCK_ENERGY = 76,
        FIGHT_PROP_CUR_FIRE_ENERGY = 1000,
        FIGHT_PROP_CUR_ELEC_ENERGY = 1001,
        FIGHT_PROP_CUR_WATER_ENERGY = 1002,
        FIGHT_PROP_CUR_GRASS_ENERGY = 1003,
        FIGHT_PROP_CUR_WIND_ENERGY = 1004,
        FIGHT_PROP_CUR_ICE_ENERGY = 1005,
        FIGHT_PROP_CUR_ROCK_ENERGY = 1006,
        FIGHT_PROP_CUR_HP = 1010,
        FIGHT_PROP_MAX_HP = 2000,
        FIGHT_PROP_CUR_ATTACK = 2001,
        FIGHT_PROP_CUR_DEFENSE = 2002,
        FIGHT_PROP_CUR_SPEED = 2003
    }
}
